comment: false
codecov:
  branch: main
  require_ci_to_pass: true
  notify:
    after_n_builds: 12
    wait_for_ci: true
  # the coverage is uploaded with or without a token. This only helps with some
  # codecov errors. It's a recommended action from here:
  # https://github.com/codecov/codecov-action/issues/837#issuecomment-1453877750
  token: 79395387-e193-4b18-b2ee-74a3b8dce269
ignore:
  - "skops/_min_dependencies.py"  # This file is not tested, and won't be.
